FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y \
    sudo \
    wget \
    gzip \
    kpartx \
    parted \
    python3 \
    python3-pip \
    python3-venv \
    qemu-user-static \
    curl \
    git \
    util-linux \
    && apt-get clean
RUN echo "root ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
WORKDIR /workspace
CMD ["/bin/bash"]