FROM ubuntu:22.04

# 安装系统依赖
RUN apt-get update && \
    apt-get install -y \
    sudo \
    wget \
    gzip \
    kpartx \
    losetup \
    parted \
    python3 \
    python3-pip \
    python3-venv \
    qemu-user-static \
    curl \
    git \
    && apt-get clean

# 配置sudo权限
RUN echo "root ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# 设置工作目录
WORKDIR /workspace

# 默认命令
CMD ["/bin/bash"] 